# Generated by Django 3.0.5 on 2020-04-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35, null=True)),
                ('type', models.CharField(max_length=25, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
